//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_luat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadMenu
    {
        public int Id { get; set; }
        public string TenMenu { get; set; }
        public string Link { get; set; }
        public Nullable<int> IdCha { get; set; }
        public string Icon { get; set; }
        public int IdUser { get; set; }
    }
}
