//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_luat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Post_DuyetLog
    {
        public int Id { get; set; }
        public Nullable<int> PostId { get; set; }
        public Nullable<int> BuocDuyet { get; set; }
        public Nullable<int> NguoiXuLy { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayXuLy { get; set; }
    }
}
