//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_luat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SuKien
    {
        public int Id { get; set; }
        public string TieuDe { get; set; }
        public Nullable<System.DateTime> NgaySuKien { get; set; }
        public Nullable<System.TimeSpan> Link { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Image { get; set; }
        public string DiaDiem { get; set; }
        public string ChuTich { get; set; }
        public string DeTai { get; set; }
        public string Nganh { get; set; }
        public string NCS { get; set; }
    }
}
