//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_luat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ThongBao
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string File { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> NgayPhatHanh { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> IdCategory { get; set; }
        public Nullable<int> IdDonVi { get; set; }
        public Nullable<int> IdLanguge { get; set; }
        public string MaThongBao { get; set; }
    }
}
