//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_luat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Post
    {
        public int ID { get; set; }
        public string TieuDe { get; set; }
        public string MoTaNgan { get; set; }
        public string Image { get; set; }
        public string NoiDung { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> View { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> NgayPhatHanh { get; set; }
        public string TacGia { get; set; }
        public Nullable<int> IdChuyenMuc { get; set; }
        public Nullable<int> IdDonVi { get; set; }
        public string Nguon { get; set; }
        public Nullable<int> BuocDuyet { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<bool> IsNoiBat { get; set; }
        public string Link { get; set; }
        public Nullable<bool> IsTab { get; set; }
        public Nullable<int> STTUuTien { get; set; }
        public Nullable<int> IdPostCu { get; set; }
        public Nullable<int> CatID { get; set; }
        public Nullable<int> PageID { get; set; }
    }
}
