//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_luat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VanBan
    {
        public int ID { get; set; }
        public string TieuDe { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string LinkFile { get; set; }
        public string LoaiVB { get; set; }
        public Nullable<System.DateTime> NgayBH { get; set; }
        public string CoQuanBanHanh { get; set; }
        public string SoHieuVB { get; set; }
        public string NguoiKy { get; set; }
    }
}
