//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_luat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NhanSu
    {
        public int Id { get; set; }
        public string TenNhanSu { get; set; }
        public string Image { get; set; }
        public string ChucVu { get; set; }
        public string GioiThieu { get; set; }
    }
}
