//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_luat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DoiTac
    {
        public int Id { get; set; }
        public string TenDoiTac { get; set; }
        public string Link { get; set; }
        public string AnhDaiDien { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
