//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_luat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GioiThieu
    {
        public int Id { get; set; }
        public string TieuDeChinh { get; set; }
        public string NoiDung { get; set; }
        public string Image { get; set; }
        public string Link { get; set; }
        public string TieuDePhu { get; set; }
        public Nullable<int> IdDonVi { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string HomThu { get; set; }
        public string Fax { get; set; }
        public string Website { get; set; }
        public string Bac { get; set; }
        public string Mau { get; set; }
    }
}
