//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_luat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MenuPage
    {
        public int Id { get; set; }
        public string TenDonVi { get; set; }
        public Nullable<int> IdCha { get; set; }
        public Nullable<int> STT { get; set; }
        public string Link { get; set; }
        public Nullable<int> IdChuyenMuc { get; set; }
        public Nullable<int> IdBaiViet { get; set; }
        public Nullable<int> IdLoaiVB { get; set; }
        public Nullable<int> IdDonVi { get; set; }
        public Nullable<int> TrenDuoi { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
