//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_luat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ThuVienAnh_Album
    {
        public int Id { get; set; }
        public string FileImage { get; set; }
        public Nullable<int> IdThuVienImage { get; set; }
        public string MoTa { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> STT { get; set; }
    }
}
